/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Service banner with the effective, redacted configuration.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit
         * @description Append-only audit log, newest first.
         */
        get: operations["get_audit_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Reset
         * @description Clear LineageMedic-owned state only.
         *
         *     Does not touch DataHub, and does not rebuild the warehouse. Use
         *     ``scripts/setup.ps1`` to regenerate the SQLite database.
         */
        post: operations["demo_reset_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose
         * @description Run the seven-agent workflow. Performs no mutation.
         */
        post: operations["diagnose_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Does not touch DataHub.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incidents
         * @description All diagnoses computed since the last reset, newest first.
         */
        get: operations["list_incidents_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Record a human decision on the remediation plan.
         */
        post: operations["approve_incidents__incident_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence
         * @description Evidence and the MCP call trace backing one incident.
         */
        get: operations["get_evidence_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/writeback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Writeback
         * @description Write incident knowledge to DataHub. Requires prior approval.
         */
        post: operations["writeback_incidents__incident_id__writeback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description The runnable scenarios, ordered worst-expected-case first.
         */
        get: operations["list_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/datahub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Datahub Status
         * @description Report DataHub connectivity truthfully, including when it is absent.
         */
        get: operations["datahub_status_status_datahub_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Integration Status
         * @description Consolidated status for the UI status bar.
         */
        get: operations["integration_status_status_integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp Status
         * @description List MCP tools available, and the calls the last diagnosis made.
         */
        get: operations["mcp_status_status_mcp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionRisk
         * @description How dangerous a proposed remediation action is.
         * @enum {string}
         */
        ActionRisk: "safe" | "reversible" | "destructive";
        /**
         * AgentName
         * @description The seven workflow agents, in execution order.
         * @enum {string}
         */
        AgentName: "quality" | "context" | "impact" | "root_cause" | "remediation" | "safety" | "writeback";
        /**
         * AgentStep
         * @description One agent's execution record, for the UI timeline.
         */
        AgentStep: {
            agent: components["schemas"]["AgentName"];
            /** Duration Ms */
            duration_ms: number;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Mcp Calls */
            mcp_calls?: components["schemas"]["McpCallRecord"][];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /**
             * Approved
             * @description True to approve the plan, False to reject it.
             */
            approved: boolean;
            /**
             * Approver
             * @description Who made the decision. Recorded in the audit log.
             * @default operator
             */
            approver: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            approval_state: components["schemas"]["ApprovalState"];
            /** Incident Id */
            incident_id: string;
            /** Message */
            message: string;
        };
        /**
         * ApprovalState
         * @description Human approval gate state for a remediation plan.
         * @enum {string}
         */
        ApprovalState: "pending" | "approved" | "rejected" | "not_required";
        /**
         * Asset
         * @description A node in the lineage graph: dataset, feature table, model, or endpoint.
         */
        Asset: {
            /** Datahub Url */
            datahub_url?: string | null;
            /** Description */
            description?: string | null;
            /** Downstreams */
            downstreams?: string[];
            kind: components["schemas"]["AssetKind"];
            /** Name */
            name: string;
            /** Owners */
            owners?: components["schemas"]["Owner"][];
            /** Platform */
            platform: string;
            /** Schema Fields */
            schema_fields?: components["schemas"]["SchemaField"][];
            source: components["schemas"]["DataSource"];
            /** Tags */
            tags?: string[];
            /** Upstreams */
            upstreams?: string[];
            /** Urn */
            urn: string;
        };
        /**
         * AssetKind
         * @description The kind of node in the lineage graph.
         * @enum {string}
         */
        AssetKind: "dataset" | "feature_table" | "ml_model" | "endpoint";
        /**
         * AuditEvent
         * @description An append-only record of something the application did.
         */
        AuditEvent: {
            /**
             * Actor
             * @default system
             */
            actor: string;
            /** Event Id */
            event_id: string;
            /** Incident Id */
            incident_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "diagnosis_started" | "diagnosis_completed" | "approval_requested" | "approval_granted" | "approval_rejected" | "writeback_attempted" | "writeback_applied" | "writeback_blocked" | "demo_reset";
            /** Message */
            message: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /**
         * CheckStatus
         * @description Outcome of a single data-quality check.
         * @enum {string}
         */
        CheckStatus: "pass" | "fail";
        /** DataHubStatusResponse */
        DataHubStatusResponse: {
            /** Connected */
            connected: boolean;
            /** Detail */
            detail: string;
            /** Fixture Mode Notice */
            fixture_mode_notice: string | null;
            /** Frontend Url */
            frontend_url: string;
            /** Gms Url */
            gms_url: string;
            /** Token Configured */
            token_configured: boolean;
        };
        /**
         * DataSource
         * @description Where a piece of context actually came from.
         *
         *     This is the anti-fabrication primitive. ``FIXTURE`` is surfaced in the API
         *     and rendered as a banner in the UI so a demo can never be mistaken for a
         *     live DataHub reading.
         * @enum {string}
         */
        DataSource: "live_datahub" | "fixture";
        /** DiagnoseRequest */
        DiagnoseRequest: {
            /**
             * Scenario Id
             * @description Scenario to run. See GET /scenarios.
             */
            scenario_id: string;
        };
        /**
         * Diagnosis
         * @description The complete structured output of one workflow run.
         *
         *     This is the object the API returns and the UI renders. It is fully
         *     self-describing: severity, evidence, impact, remediation, approval state,
         *     and the provenance of every DataHub fact it relied on.
         */
        Diagnosis: {
            approval_state: components["schemas"]["ApprovalState"];
            /** Confidence */
            confidence: number;
            /** Confidence Explanation */
            confidence_explanation: string;
            context_source: components["schemas"]["DataSource"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Fixture Mode Notice */
            fixture_mode_notice?: string | null;
            impact: components["schemas"]["ImpactAssessment"];
            /** Incident Id */
            incident_id: string;
            lineage: components["schemas"]["LineageGraph"];
            /** Mcp Calls */
            mcp_calls?: components["schemas"]["McpCallRecord"][];
            /** Narration */
            narration?: string | null;
            /**
             * Narration Provider
             * @default deterministic
             */
            narration_provider: string;
            /** Quality Checks */
            quality_checks?: components["schemas"]["QualityCheck"][];
            /** Remediation */
            remediation?: components["schemas"]["RemediationAction"][];
            /** Root Causes */
            root_causes?: components["schemas"]["RootCauseHypothesis"][];
            safety: components["schemas"]["SafetyVerdict"];
            /** Scenario Id */
            scenario_id: string;
            severity: components["schemas"]["Severity"];
            /** Steps */
            steps?: components["schemas"]["AgentStep"][];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            writeback?: components["schemas"]["WritebackReceipt"] | null;
        };
        /**
         * EvidenceItem
         * @description A single human-readable fact backing a conclusion.
         *
         *     Evidence is what LineageMedic shows instead of chain-of-thought: each item
         *     names its origin agent and points at the artifact it was derived from.
         */
        EvidenceItem: {
            agent: components["schemas"]["AgentName"];
            /** Detail */
            detail: string;
            /** Label */
            label: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at?: string;
            /** References */
            references?: string[];
            source: components["schemas"]["DataSource"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database Present */
            database_present: boolean;
            /** Mode */
            mode: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * ImpactAssessment
         * @description The full affected/unaffected partition for an incident.
         */
        ImpactAssessment: {
            /** Affected Count */
            affected_count: number;
            /** Assets */
            assets: components["schemas"]["ImpactedAsset"][];
            /** Ml Models Affected */
            ml_models_affected?: string[];
            /** Production Endpoints Affected */
            production_endpoints_affected?: string[];
            /** Source Urn */
            source_urn: string;
            /** Unaffected Count */
            unaffected_count: number;
        };
        /**
         * ImpactState
         * @description Whether an asset lies in the blast radius of an incident.
         * @enum {string}
         */
        ImpactState: "affected" | "unaffected" | "source";
        /**
         * ImpactedAsset
         * @description An asset classified against the blast radius, with the reason why.
         */
        ImpactedAsset: {
            /** Hops From Source */
            hops_from_source?: number | null;
            kind: components["schemas"]["AssetKind"];
            /** Name */
            name: string;
            /** Rationale */
            rationale: string;
            state: components["schemas"]["ImpactState"];
            /** Urn */
            urn: string;
        };
        /**
         * IntegrationStatus
         * @description Live status of each external dependency, for the UI status bar.
         */
        IntegrationStatus: {
            /** Datahub Connected */
            datahub_connected: boolean;
            /** Datahub Detail */
            datahub_detail: string;
            /** Fixture Mode Notice */
            fixture_mode_notice?: string | null;
            /** Llm Available */
            llm_available: boolean;
            /** Llm Detail */
            llm_detail: string;
            /** Llm Provider */
            llm_provider: string;
            /** Mcp Connected */
            mcp_connected: boolean;
            /** Mcp Detail */
            mcp_detail: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "fixture" | "live";
        };
        /**
         * LineageGraph
         * @description The subgraph retrieved for one incident, plus its provenance.
         */
        LineageGraph: {
            /** Assets */
            assets: components["schemas"]["Asset"][];
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at?: string;
            source: components["schemas"]["DataSource"];
        };
        /**
         * McpCallRecord
         * @description An audit record of one MCP tool invocation.
         *
         *     Recorded for every call regardless of outcome, so the UI can prove which
         *     tools ran, with what (sanitized) arguments, and what URNs came back.
         */
        McpCallRecord: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /**
             * Called At
             * Format: date-time
             */
            called_at?: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
            /** Returned Urns */
            returned_urns?: string[];
            source: components["schemas"]["DataSource"];
            /** Tool */
            tool: string;
        };
        /** McpCapabilityResponse */
        McpCapabilityResponse: {
            /** Connected */
            connected: boolean;
            /** Detail */
            detail: string;
            /** Recent Calls */
            recent_calls: components["schemas"]["McpCallRecord"][];
            /** Source */
            source: string;
            /** Tools */
            tools: string[];
        };
        /**
         * Owner
         * @description An owning user or group.
         *
         *     ``contact`` is a team channel or distribution list, never a personal email
         *     address — fixtures use role accounts so no personal information ships in the
         *     repository.
         */
        Owner: {
            /** Contact */
            contact?: string | null;
            /** Display Name */
            display_name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "TECHNICAL_OWNER" | "BUSINESS_OWNER" | "DATA_STEWARD";
            /** Urn */
            urn: string;
        };
        /**
         * QualityCheck
         * @description One executed data-quality check and its measured result.
         *
         *     These numbers come from really querying the bundled SQLite database — they
         *     are computed, never hard-coded.
         */
        QualityCheck: {
            /** Check Id */
            check_id: string;
            /** Column */
            column?: string | null;
            /**
             * Comparison
             * @enum {string}
             */
            comparison: "lte" | "gte" | "eq";
            /** Dataset Urn */
            dataset_urn: string;
            /** Description */
            description: string;
            /**
             * Failing Rows
             * @default 0
             */
            failing_rows: number;
            /** Observed Value */
            observed_value: number;
            /** Rows Scanned */
            rows_scanned: number;
            /** Sample Failing Values */
            sample_failing_values?: string[];
            status: components["schemas"]["CheckStatus"];
            /** Threshold */
            threshold: number;
        };
        /**
         * RemediationAction
         * @description A single proposed corrective step.
         *
         *     ``rollback`` is required for anything not classified ``SAFE``: the
         *     Remediation Agent may not propose a step it cannot describe undoing.
         */
        RemediationAction: {
            /** Action Id */
            action_id: string;
            /** Description */
            description: string;
            /** Requires Approval */
            requires_approval: boolean;
            /** Reversible */
            reversible: boolean;
            risk: components["schemas"]["ActionRisk"];
            /** Rollback */
            rollback?: string | null;
            /** Target Urn */
            target_urn: string;
            /** Title */
            title: string;
        };
        /** ResetResponse */
        ResetResponse: {
            /** Cleared Incidents */
            cleared_incidents: number;
            /** Message */
            message: string;
        };
        /**
         * RootCauseHypothesis
         * @description One ranked candidate explanation for the observed failure.
         */
        RootCauseHypothesis: {
            /** Confidence */
            confidence: number;
            /** Reasoning */
            reasoning: string;
            /** Summary */
            summary: string;
            /** Supporting Evidence */
            supporting_evidence?: string[];
            /** Suspected Urn */
            suspected_urn: string;
        };
        /**
         * SafetyVerdict
         * @description The Safety Agent's ruling on a remediation plan.
         */
        SafetyVerdict: {
            /** Approved Actions */
            approved_actions: string[];
            /** Blocked Actions */
            blocked_actions: string[];
            /** Blocking Reasons */
            blocking_reasons?: {
                [key: string]: string;
            };
            /** Notes */
            notes?: string[];
            /** Requires Human Approval */
            requires_human_approval: boolean;
        };
        /**
         * ScenarioSummary
         * @description Catalog entry for a runnable scenario.
         */
        ScenarioSummary: {
            /** Description */
            description: string;
            expected_severity: components["schemas"]["Severity"];
            /** Scenario Id */
            scenario_id: string;
            /** Title */
            title: string;
        };
        /**
         * SchemaField
         * @description One column of a dataset schema, as reported by DataHub.
         */
        SchemaField: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Native Type */
            native_type: string;
            /**
             * Nullable
             * @default true
             */
            nullable: boolean;
        };
        /**
         * Severity
         * @description Incident severity, ordered.
         * @enum {string}
         */
        Severity: "critical" | "warning" | "healthy";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WritebackReceipt
         * @description Proof (or honest refusal) of a DataHub metadata mutation.
         *
         *     In fixture mode this is always ``SKIPPED_FIXTURE_MODE`` with an empty
         *     ``aspects_written``. The application never emits ``APPLIED`` unless a live
         *     adapter reported a real, verified mutation.
         */
        WritebackReceipt: {
            /** Aspects Written */
            aspects_written?: string[];
            /**
             * Attempted At
             * Format: date-time
             */
            attempted_at?: string;
            /** Datahub Urls */
            datahub_urls?: string[];
            /** Error */
            error?: string | null;
            /** Note */
            note: string;
            source: components["schemas"]["DataSource"];
            status: components["schemas"]["WritebackStatus"];
            /** Tags Added */
            tags_added?: string[];
            /** Target Urns */
            target_urns?: string[];
        };
        /**
         * WritebackStatus
         * @description Terminal state of an attempted DataHub metadata writeback.
         * @enum {string}
         */
        WritebackStatus: "applied" | "blocked_pending_approval" | "skipped_fixture_mode" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_audit_audit_get: {
        parameters: {
            query?: {
                incident_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_reset_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
        };
    };
    diagnose_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_incidents_incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"][];
                };
            };
        };
    };
    get_incident_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnosis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_incidents__incident_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_incidents__incident_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    writeback_incidents__incident_id__writeback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritebackReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    datahub_status_status_datahub_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataHubStatusResponse"];
                };
            };
        };
    };
    integration_status_status_integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatus"];
                };
            };
        };
    };
    mcp_status_status_mcp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpCapabilityResponse"];
                };
            };
        };
    };
}
